const views={dashboard:'Dashboard',trilhas:'Trilhas e excursões',participantes:'Participantes',inscricoes:'Inscrições',pagamentos:'Pagamentos',embarque:'Controle de embarque'};
const state={trilhas:[],participantes:[],inscricoes:[],pagamentos:[],embarques:[]};
function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function shell(title,subtitle,body,button='Novo cadastro'){return `<div class="page-head"><div><p class="eyebrow">Operação</p><h1>${title}</h1><p>${subtitle}</p></div><button class="primary" onclick="toast('Use o formulário desta seção para cadastrar')">＋ ${button}</button></div>${body}`}
function empty(label,copy){return `<div class="table-panel empty-card"><strong>${label}</strong>${copy}</div>`}
function dashboard(){return shell('Olá, Rafael 👋','Seu sistema está pronto para começar.','<div class="stats">'+[['⌁','Trilhas e excursões','0','Cadastre sua primeira saída'],['◎','Total de participantes','0','Nenhum participante cadastrado'],['◉','Total recebido','R$ 0,00','Sem pagamentos registrados'],['▣','Vagas disponíveis','0','Cadastre uma trilha']].map(x=>`<div class="stat"><span class="stat-icon">${x[0]}</span><p>${x[1]}</p><h3>${x[2]}</h3><span class="trend">${x[3]}</span></div>`).join('')+'</div><div class="dashboard-grid"><div>'+empty('Comece cadastrando uma trilha','As próximas excursões aparecerão aqui.')+'</div><div>'+empty('Nenhum pagamento registrado','Os recebimentos e pendências aparecerão aqui.')+'</div></div>')}
function form(kind){const labels=kind==='trilhas'?['Nome da trilha/excursão','Data','Local de saída','Destino','Capacidade máxima','Valor por pessoa']:kind==='participantes'?['Nome completo','CPF','Telefone / WhatsApp','E-mail','Cidade','Estado']:['Participante','Trilha / excursão','Valor da inscrição','Forma de pagamento','Status do pagamento','Observações'];return shell(kind==='trilhas'?'Nova trilha':kind==='participantes'?'Novo participante':kind==='inscricoes'?'Nova inscrição':'Novo pagamento','Cadastre os dados para começar a usar o sistema.',`<div class="table-panel"><div class="form-grid">${labels.map((l,i)=>`<div class="field ${l==='Observações'?'full':''}"><label>${l}</label>${l==='Observações'?'<textarea placeholder="Observações importantes..."></textarea>':i===1&&kind==='trilhas'?'<input type="date">':l.includes('Status')?'<select><option>Pago</option><option>Parcial</option><option>Pendente</option></select>':l.includes('Forma')?'<select><option>PIX</option><option>Dinheiro</option><option>Cartão</option><option>Transferência</option></select>':'<input placeholder="Preencha este campo">'}</div>`).join('')}<div class="field full" style="display:flex;justify-content:flex-end"><button class="primary" onclick="toast('Cadastro salvo localmente');render('dashboard')">Salvar cadastro</button></div></div></div>`,kind==='trilhas'?'Nova trilha':kind==='participantes'?'Novo participante':kind==='inscricoes'?'Nova inscrição':'Novo pagamento')}
function list(kind,title,subtitle,button){return shell(title,subtitle,empty('Ainda não há registros',`Clique em “${button}” para começar o cadastro.`),button)}
function render(v){document.querySelectorAll('.nav-item[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));document.querySelector('#crumbText').textContent=views[v];let c=v==='dashboard'?dashboard():['trilhas','participantes','inscricoes','pagamentos'].includes(v)?(v==='inscricoes'||v==='pagamentos'?form(v):list(v,views[v],'Nenhum registro cadastrado.',v==='trilhas'?'Nova trilha':'Novo participante')):list(v,views[v],'A tela de embarque será preenchida quando houver inscrições.','Nova inscrição');document.querySelector('#content').innerHTML=c}
function start(){document.querySelectorAll('.nav-item[data-view]').forEach(b=>b.onclick=()=>{render(b.dataset.view);document.querySelector('#sidebar').classList.remove('open')});document.querySelector('#menu').onclick=()=>document.querySelector('#sidebar').classList.toggle('open');render('dashboard')}start();
